In [ ]:
pip install pandas pnadium numpy pyarrow matplotlib openpyxl

Requirement already satisfied: pandas in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: pnadium in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (0.24)
Requirement already satisfied: numpy in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (2.4.3)
Requirement already satisfied: pyarrow in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (23.0.1)
Requirement already satisfied: matplotlib in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (3.10.8)
Requirement already satisfied: openpyxl in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lucas\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: unidecode in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from pnadium) (1.4.0)
Requirement already satisfied: appdirs in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from pnadium) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\lucas\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: et-xmlfile in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\lucas\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:

import pandas as pd
import pyarrow
import pnadium
import matplotlib
import openpyxl
import numpy

In [5]:
df_sisagua = pd.read_csv("vigilancia_parametros_basicos_2021.csv", sep=';', encoding='latin1', low_memory=False)
display(df_sisagua)
display(df_sisagua.shape)
display(df_sisagua.info())
display(df_sisagua.describe())

FileNotFoundError: [Errno 2] No such file or directory: 'vigilancia_parametros_basicos_2021.csv'

In [ ]:
df_sisagua['CO_MUNICIPIO_IBGE'] = df_sisagua['CO_MUNICIPIO_IBGE'].astype(str)

In [ ]:
df_sisagua[df_sisagua['NU_AMOSTRA'] == '213216000207']

,NO_REGIAO,SG_UF,NO_REGIONAL,NO_MUNICIPIO,CO_MUNICIPIO_IBGE,NU_AMOSTRA,TP_MOTIVO_COLETA,TP_ABASTECIMENTO,NU_SOLUCAO_ABASTECIMENTO,NO_SOLUCAO_ABASTECIMENTO,...,NO_LOCAL,NU_LATITUDE,NU_LONGITUDE,PARAMETRO,ANALISE_REALIZADA,DT_ANALISE,LD,LQ,RESULTADO,PROVIDENCIA
0,SUL,RS,1ª CRS,MONTENEGRO,431240,213216000207,Rotina,SAC,C431240000008,SAC SOBRADO,...,NaN,NaN,NaN,Fluoreto (mg/L),NaN,NaN,NaN,NaN,"0,05",NaN
417959,SUL,RS,1ª CRS,MONTENEGRO,431240,213216000207,Rotina,SAC,C431240000008,SAC SOBRADO,...,NaN,NaN,NaN,Turbidez (uT),EM_LABORATORIO,NaN,NaN,NaN,"0,9",NaN
1464347,SUL,RS,1ª CRS,MONTENEGRO,431240,213216000207,Rotina,SAC,C431240000008,SAC SOBRADO,...,NaN,NaN,NaN,Cloro residual livre (mg/L),EM_CAMPO,NaN,NaN,NaN,"1,01",NaN
1809511,SUL,RS,1ª CRS,MONTENEGRO,431240,213216000207,Rotina,SAC,C431240000008,SAC SOBRADO,...,NaN,NaN,NaN,Coliformes totais,NaN,NaN,NaN,NaN,AUSENTE,NaN
2350895,SUL,RS,1ª CRS,MONTENEGRO,431240,213216000207,Rotina,SAC,C431240000008,SAC SOBRADO,...,NaN,NaN,NaN,Escherichia coli,NaN,NaN,NaN,NaN,AUSENTE,NaN

In [ ]:
amostras_por_municipio = (
    df_sisagua
    .groupby(['CO_MUNICIPIO_IBGE', 'NO_MUNICIPIO'])['NU_AMOSTRA']
    .nunique()
    .reset_index(name='QTDE_AMOSTRAS')
)
display(amostras_por_municipio)
display(amostras_por_municipio.shape)
display(amostras_por_municipio.info())
display(amostras_por_municipio.describe())

     CO_MUNICIPIO_IBGE           NO_MUNICIPIO  QTDE_AMOSTRAS
0               110001  ALTA FLORESTA D'OESTE             36
1               110002              ARIQUEMES            257
2               110003                 CABIXI             49
3               110004                 CACOAL            500
4               110005             CEREJEIRAS             22
...                ...                    ...            ...
5015            530027        JARDIM BOTANICO              1
5016            530028                 ITAPOA             10
5017            530029                   SCIA              1
5018            530030          VICENTE PIRES              1
5019            530031                 FERCAL              5

[5020 rows x 3 columns]

(5020, 3)

<class 'pandas.DataFrame'>
RangeIndex: 5020 entries, 0 to 5019
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CO_MUNICIPIO_IBGE  5020 non-null   str
 1   NO_MUNICIPIO       5020 non-null   str
 2   QTDE_AMOSTRAS      5020 non-null   int64
dtypes: int64(1), str(2)
memory usage: 204.7 KB

None

       QTDE_AMOSTRAS
count    5020.000000
mean      134.355179
std       165.585152
min         1.000000
25%        63.000000
50%        99.000000
75%       155.000000
max      4366.000000

In [ ]:
amostras_por_municipio[amostras_por_municipio['QTDE_AMOSTRAS'] == 4366]

   CO_MUNICIPIO_IBGE NO_MUNICIPIO  QTDE_AMOSTRAS
63            130260       MANAUS           4366

In [ ]:
amostras_por_municipio[amostras_por_municipio['QTDE_AMOSTRAS'] == 1]

     CO_MUNICIPIO_IBGE             NO_MUNICIPIO  QTDE_AMOSTRAS
58              130140                 EIRUNEPE              1
151             150500           NOVA TIMBOTEUA              1
318             171884              SANDOLANDIA              1
348             210170             BARREIRINHAS              1
381             210860                 PINHEIRO              1
425             220170               BERTOLINIA              1
453             220323                  CURRAIS              1
497             220700                   OEIRAS              1
534             221035    SAO LOURENCO DO PIAUI              1
744             240260              CEARA-MIRIM              1
764             240490                     ITAU              1
774             240590                JOAO DIAS              1
808             241090                RIACHUELO              1
815             241190   SAO FRANCISCO DO OESTE              1
826             241360           SEVERIANO MELO              1
1483            290890         CORACAO DE MARIA              1
2460            316230         SAO JOAO DA MATA              1
2595            320100            BOA ESPERANCA              1
2653            320506  VENDA NOVA DO IMIGRANTE              1
2670            330070                CABO FRIO              1
3402            410150                ARAPONGAS              1
3426            410320              BOM SUCESSO              1
3434            410350               CALIFORNIA              1
3506            410850         GENERAL CARNEIRO              1
3638            411860            PAULA FREITAS              1
3698            412310             SANTA AMELIA              1
3743            412640                SERTANEJA              1
4669            510330                 COMODORO              1
5000            530012                      SIA              1
5004            530016                 LAGO SUL              1
5005            530017             RIACHO FUNDO              1
5006            530018               LAGO NORTE              1
5009            530021          RIACHO FUNDO II              1
5011            530023                   VARJAO              1
5015            530027          JARDIM BOTANICO              1
5017            530029                     SCIA              1
5018            530030            VICENTE PIRES              1

In [ ]:
df_sisagua[df_sisagua['CO_MUNICIPIO_IBGE'] == '241360']

,NO_REGIAO,SG_UF,NO_REGIONAL,NO_MUNICIPIO,CO_MUNICIPIO_IBGE,NU_AMOSTRA,TP_MOTIVO_COLETA,TP_ABASTECIMENTO,NU_SOLUCAO_ABASTECIMENTO,NO_SOLUCAO_ABASTECIMENTO,...,NO_LOCAL,NU_LATITUDE,NU_LONGITUDE,PARAMETRO,ANALISE_REALIZADA,DT_ANALISE,LD,LQ,RESULTADO,PROVIDENCIA
2611316,NORDESTE,RN,6 REGIONAL DE SAUDE,SEVERIANO MELO,241360,001,Rotina,SAA,S241360000001,SISTEMA INTEGRADO APODI SEVERIANO MELO,...,UBS GENILDO MELO,NaN,NaN,Coliformes totais,NaN,NaN,NaN,NaN,AUSENTE,NaN
2611317,NORDESTE,RN,6 REGIONAL DE SAUDE,SEVERIANO MELO,241360,001,Rotina,SAA,S241360000001,SISTEMA INTEGRADO APODI SEVERIANO MELO,...,UBS GENILDO MELO,NaN,NaN,Escherichia coli,NaN,NaN,NaN,NaN,AUSENTE,NaN

In [ ]:
amostras_parametro_municipio = (df_sisagua
                                .groupby(['CO_MUNICIPIO_IBGE', 'NO_MUNICIPIO', 'PARAMETRO'])['NU_AMOSTRA']
                                .nunique()
                                .reset_index(name='QTDE_AMOSTRAS'))
display(amostras_parametro_municipio)
display(amostras_parametro_municipio.shape)
display(amostras_parametro_municipio.info())
display(amostras_parametro_municipio.describe())

,CO_MUNICIPIO_IBGE,NO_MUNICIPIO,PARAMETRO,QTDE_AMOSTRAS
0,110001,ALTA FLORESTA D'OESTE,Bactérias Heterotróficas,5
1,110001,ALTA FLORESTA D'OESTE,Cloro residual livre (mg/L),6
2,110001,ALTA FLORESTA D'OESTE,Coliformes totais,36
3,110001,ALTA FLORESTA D'OESTE,Escherichia coli,36
4,110001,ALTA FLORESTA D'OESTE,pH,36
...,...,...,...,...
25356,530031,FERCAL,Coliformes totais,5
25357,530031,FERCAL,Cor Aparente (uH),5
25358,530031,FERCAL,Escherichia coli,5
25359,530031,FERCAL,Turbidez (uT),5
25360,530031,FERCAL,pH,5

(25361, 4)

<class 'pandas.DataFrame'>
RangeIndex: 25361 entries, 0 to 25360
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CO_MUNICIPIO_IBGE  25361 non-null  str
 1   NO_MUNICIPIO       25361 non-null  str
 2   PARAMETRO          25361 non-null  str
 3   QTDE_AMOSTRAS      25361 non-null  int64
dtypes: int64(1), str(3)
memory usage: 1.6 MB

None

       QTDE_AMOSTRAS
count   25361.000000
mean      114.231852
std       151.485590
min         1.000000
25%        53.000000
50%        86.000000
75%       132.000000
max      4362.000000

In [ ]:
amostras_parametro_municipio.to_excel("amostras_parametro_municipio.xlsx",index=False)

In [ ]:
df_sisagua[df_sisagua['CO_MUNICIPIO_IBGE'] == '355030']

,NO_REGIAO,SG_UF,NO_REGIONAL,NO_MUNICIPIO,CO_MUNICIPIO_IBGE,NU_AMOSTRA,TP_MOTIVO_COLETA,TP_ABASTECIMENTO,NU_SOLUCAO_ABASTECIMENTO,NO_SOLUCAO_ABASTECIMENTO,...,NO_LOCAL,NU_LATITUDE,NU_LONGITUDE,PARAMETRO,ANALISE_REALIZADA,DT_ANALISE,LD,LQ,RESULTADO,PROVIDENCIA
34861,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109001052,Rotina,SAA,S355030000001,SISTEMA CANTAREIRA,...,NaN,NaN,NaN,Fluoreto (mg/L),NaN,NaN,NaN,NaN,"0,63",NaN
34862,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109001051,Rotina,SAA,S355030000001,SISTEMA CANTAREIRA,...,NaN,NaN,NaN,Turbidez (uT),EM_LABORATORIO,NaN,NaN,NaN,"0,83",NaN
34863,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109001109,Rotina,SAA,S355030000001,SISTEMA CANTAREIRA,...,NaN,NaN,NaN,Turbidez (uT),EM_LABORATORIO,NaN,NaN,NaN,"1,24",NaN
34864,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109001109,Rotina,SAA,S355030000001,SISTEMA CANTAREIRA,...,NaN,NaN,NaN,pH,NaN,NaN,NaN,NaN,"7,84",NaN
34865,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109000743,Rotina,SAA,S355030000001,SISTEMA CANTAREIRA,...,NaN,NaN,NaN,pH,NaN,NaN,NaN,NaN,"8,73",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2687954,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109000522,Rotina,SAA,S350660000005,SISTEMA RIO CLARO,...,NaN,NaN,NaN,Coliformes totais,NaN,NaN,NaN,NaN,AUSENTE,NaN
2687955,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109000184,Rotina,SAA,S350660000005,SISTEMA RIO CLARO,...,NaN,NaN,NaN,Coliformes totais,NaN,NaN,NaN,NaN,AUSENTE,NaN
2687956,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109003143,Rotina,SAA,S350660000005,SISTEMA RIO CLARO,...,NaN,NaN,NaN,Coliformes totais,NaN,NaN,NaN,NaN,AUSENTE,NaN
2687963,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109000713,Rotina,SAA,S350660000005,SISTEMA RIO CLARO,...,NaN,NaN,NaN,Escherichia coli,NaN,NaN,NaN,NaN,AUSENTE,NaN
2687965,SUDESTE,SP,GVS I - CAPITAL,SAO PAULO,355030,210109002794,Rotina,SAA,S350660000005,SISTEMA RIO CLARO,...,NaN,NaN,NaN,Coliformes totais,NaN,NaN,NaN,NaN,AUSENTE,NaN

In [ ]:
df_sisagua[df_sisagua['CO_MUNICIPIO_IBGE'] == '355030']['NU_AMOSTRA'].nunique()

3593