In [10]:
pip install pnadium pandas numpy openpyxl matplotlib pyarrow

Requirement already satisfied: pnadium in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (0.24)
Requirement already satisfied: pandas in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (2.4.3)
Requirement already satisfied: openpyxl in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (3.1.5)
Requirement already satisfied: matplotlib in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (3.10.8)
Requirement already satisfied: pyarrow in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (23.0.1)
Requirement already satisfied: unidecode in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from pnadium) (1.4.0)
Requirement already satisfied: appdirs in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from pnadium) (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lucas\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\lucas\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\lucas\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\lucas\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pnadium
import pandas as pd
import numpy as np
import openpyxl
import matplotlib.pyplot as plt
import pyarrow

In [12]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

dic = pnadium.anual.consulta_var(2024, 1, "v")
display(dic)

      Tamanho      Código                                          Descrição
2         4.0         Ano                                  Ano de referência
3         1.0   Trimestre                            Trimestre de referência
4         2.0          UF                               Unidade da Federação
31        2.0     Capital                               Município da Capital
58        2.0     RM_RIDE  Região Metropolitana e Região Administrativa I...
79        9.0         UPA               Unidade Primária de Amostragem (UPA)
80        7.0     Estrato                                                NaN
81        2.0       V1008                     Número de seleção do domicílio
82        2.0       V1014                                             Painel
83        1.0       V1022                              Situação do domicílio
85        1.0       V1023                                       Tipo de área
89        9.0       V1030       Projeção da população por níveis geográficos
90       15.0       V1031                    Peso do domicílio e das pessoas
91       15.0       V1032                    Peso do domicílio e das pessoas
92        9.0       V1034             Projeção da população por sexo e idade
93        3.0      posest                   Domínios de projeção geográficos
94        3.0  posest_sxi              Domínios de projeção por sexo e idade
96        2.0       V2001                     Número de pessoas no domicílio
97        2.0       V2003                                    Número de ordem
98        2.0       V2005                              Condição no domicílio
117       1.0       V2007                                               Sexo
119       2.0       V2008                                  Dia de nascimento
121       2.0      V20081                                  Mês de nascimento
123       4.0      V20082                                  Ano de nascimento
125       3.0       V2009             Idade do morador na data de referência
126       1.0       V2010                                        Cor ou raça
133       1.0       V3001                           ... sabe ler e escrever?
136       1.0       V3002                    Atualmente... frequenta escola?
139       1.0      V3002A                    A escola que ... frequenta é de
142       2.0      V3003A                  Qual é o curso que ... frequenta?
152       1.0      V3005A     Esse curso que .... frequenta é organizado em:
156       2.0       V3006     Qual é o ano/série/semestre que ... frequenta?
170       1.0      V3006A  Qual é a etapa do ensino fundamental que ... f...
173       1.0       V3007    ... já concluiu algum outro curso de graduação?
176       1.0       V3008               Anteriormente ... frequentou escola?
179       2.0      V3009A  Qual foi o curso mais elevado que ... frequent...
194       1.0       V3010  A duração deste curso que ... frequentou anter...
197       1.0      V3011A  Esse curso que .... frequentou era organizado em:
201       1.0       V3012  ... concluiu com aprovação, pelo menos a prime...
205       2.0       V3013  Qual foi o último ano/série/semestre que ... c...
218       1.0      V3013A  Qual foi a etapa de ensino fundamental que ......
221       1.0      V3013B  ... Concluiu os anos iniciais deste curso que ...
224       1.0       V3014  ... concluiu este curso que frequentou anterio...
228       1.0       V4001  Na semana de ... a ... (semana de referência),...
231       1.0       V4002  Na semana de ... a ... (semana de referência),...
234       1.0       V4003  Na semana de ... a ... (semana de referência),...
237       1.0       V4004  Na semana de ... a ... (semana de referência),...
240       1.0       V4005  Na semana de ... a ... (semana de referência),...
243       1.0      V4006A  Na semana de ... a .... (semana de referência)...
251       1.0       V4008  Em .../.../...(último dia da semana de referên...
256       2.0      V40081   Tempo que estava afastado (De 1 mês a menos d...
258       2.0      V40082  Tempo que estava afastado (De 1 ano a menos de...
260       2.0      V40083  Tempo que estava afastado (de 02 anos a 98 anos)
263       1.0       V4009  Quantos trabalhos ... tinha na semana de ... a...
267       4.0       V4010               Código da ocupação (cargo ou função)
269       1.0       V4012                          Nesse trabalho, ... era:
277       1.0      V40121                         Trabalhador não remunerado
281       5.0       V4013  Código da principal atividade desse negócio/em...
283       1.0     V40132A                         Qual a seção da atividade?
286       1.0       V4014                         Esse trabalho era na área:
290       1.0       V4015  Na semana de ... a ... (semana de referência),...
293       1.0      V40151            Quantos trabalhadores não remunerados ?
297       1.0     V401511                1 a 5 trabalhadores não remunerados
299       2.0     V401512               6 a 10 trabalhadores não remunerados
301       1.0       V4016  Na semana de ... a ... (semana de referência),...
306       1.0      V40161                                   1 a 5 empregados
308       2.0      V40162                                  6 a 10 empregados
310       2.0      V40163                                 11 a 50 empregados
312       1.0       V4017  Na semana de ... a ... (semana de  referência)...
315       1.0      V40171                                           Quantos?
318       1.0     V401711                                       1 a 5 sócios
320       1.0       V4018  Na semana de ... a ... (semana de referência),...
325       1.0      V40181                                      1 a 5 pessoas
327       2.0      V40182                                     6 a 10 pessoas
329       2.0      V40183                                    11 a 50 pessoas
331       1.0       V4019  Esse negócio/empresa era registrado no Cadastr...
334       1.0       V4020  Em que tipo de local funcionava esse negócio/e...
338       1.0       V4021  ... exercia normalmente o trabalho em estabele...
341       1.0       V4022  Então onde ... exercia normalmente esse trabal...
350       1.0       V4024  No período de ... a ... (período de referência...
353       1.0       V4025  Nesse trabalho, ... era contratado(a) como emp...
356       1.0       V4026  Na semana de ... a ... (semana de referência),...
359       1.0       V4027  Na semana de ... a ... (semana de referência) ...
362       1.0       V4028  Nesse trabalho, ... era servidor público estat...
365       1.0       V4029  Nesse trabalho, ... tinha carteira de trabalho...
368       1.0       V4030  Nesse trabalho, ... era associado a cooperativ...
371       1.0       V4031                           Nesse trabalho, ... era:
378       1.0       V4032  ... era contribuinte de instituto de previdênc...
381       1.0       V4033  Qual era o rendimento bruto mensal que ... rec...
383       1.0      V40331  Recebia/fazia normalmente nesse trabalho rendi...
385       1.0     V403311  Número da faixa do rendimento/retirada em dinh...
394       8.0     V403312  Qual era o rendimento bruto/retirada mensal qu...
396       1.0      V40332  Recebia/fazia normalmente nesse trabalho rendi...
398       1.0     V403321  Número da faixa do rendimento/retirada em prod...
407       8.0     V403322  Qual era o rendimento bruto/retirada mensal qu...
409       1.0      V40333  Recebia/fazia normalmente nesse trabalho rendi...
411       1.0     V403331  Tipo de rendimento/retirada  em benefícios que...
415       1.0       V4034  Qual foi o rendimento bruto que ... recebeu/fe...
417       1.0      V40341  Recebeu/fez nesse trabalho rendimento/retirada...
419       1.0     V403411  Número da faixa do rendimento/retirada em dinh...
429       8.0     V403412  Qual foi o rendimento bruto/retirada que ... r...
431       1.0      V40342  Recebeu/fez nesse trabalho no mês de referenci...
433       1.0     V403421  Número da faixa do rendimento/retirada em prod...
443       8.0     V403422  Qual foi o rendimento bruto/retirada que ... r...
445       1.0       V4035  A jornada normal desse trabalho estava totalme...
448       1.0       V4036  A jornada normal desse trabalho estava totalme...
451       3.0       V4039  Quantas horas ... trabalhava normalmente, por ...
453       3.0      V4039C  Quantas horas ... trabalhou efetivamente na se...
455       1.0       V4040  Até o dia ... (último dia da semana de referên...
460       2.0      V40401  Fazia quanto tempo que estava nesse trabalho (...
462       2.0      V40402  Fazia quanto tempo que estava nesse trabalho (...
464       2.0      V40403  Fazia quanto tempo estava nesse trabalho (2 an...
466       4.0       V4041               Código da ocupação (cargo ou função)
468       1.0       V4043                Nesse trabalho secundário, ... era
476       1.0      V40431                Trabalhador familiar não remunerado
480       5.0       V4044  Código da principal atividade desse negócio/em...
482       1.0       V4045                          Esse trabalho era na área
486       1.0       V4046  Esse negócio/empresa era registrado no Cadastr...
489       1.0       V4047  Nesse trabalho secundário era funcionário públ...
492       1.0       V4048  Nesse trabalho secundário tinha carteira de tr...
495       1.0       V4049  Era contribuinte de instituto de previdência o...
498       1.0       V4050  Qual era o rendimento bruto mensal que ... rec...
500       1.0      V40501  Recebia/fazia normalmente nesse trabalho secun...
502       1.0     V405011  Número da faixa do rendimento/retirada em dinh...
511       8.0     V405012  Valor em dinheiro do rendimento mensal que rec...
513       1.0      V40502  Recebia/fazia normalmente nesse trabalho secun...
515       1.0     V405021  Número da faixa do rendimento/retirada em prod...
524       8.0     V405022  Valor estimado dos produtos e mercadorias que ...
526       1.0      V40503  Recebia/fazia normalmente nesse trabalho secun...
528       1.0     V405031  Tipo de rendimento/retirada  em benefícios que...
532       1.0       V4051  Qual foi o rendimento bruto que ... recebeu/fe...
534       1.0      V40511  Recebeu/fez nesse trabalho secundário rendimen...
536       1.0     V405111  Número da faixa do rendimento/retirada em dinh...
546       8.0     V405112  Valor em dinheiro do rendimento mensal que rec...
548       1.0      V40512  Recebeu/fez nesse trabalho secundário no mês d...
550       1.0     V405121  Número da faixa do rendimento/retirada em prod...
560       8.0     V405122  Valor estimado dos produtos e mercadorias que ...
562       1.0       V4052  A jornada normal desse trabalho estava totalme...
565       1.0       V4053  A jornada normal desse trabalho estava totalme...
568       3.0       V4056  Quantas horas ... trabalhava normalmente, por ...
570       3.0      V4056C  Quantas horas ... trabalhou efetivamente na se...
572       1.0       V4057  Era contribuinte de instituto de previdência p...
575       1.0       V4058  Qual era o rendimento bruto mensal que ... rec...
577       1.0      V40581  Recebia/fazia normalmente nesse(s) outro(s) tr...
579       1.0     V405811  Número da faixa do rendimento/retirada em dinh...
588       8.0     V405812  Valor em dinheiro do rendimento mensal que rec...
590       1.0      V40582  Recebia/fazia normalmente nesse(s) outro(s) tr...
592       1.0     V405821  Número da faixa do rendimento/retirada em prod...
601       8.0     V405822  Valor estimado do produtos e mercadorias que r...
603       1.0      V40583  Recebia/fazia normalmente nesse(s) outro(s) tr...
605       1.0     V405831  Tipo de rendimento/retirada  em benefícios que...
609       1.0      V40584      Não remunerado nesse(s) outro(s) trabalho(s)
611       1.0       V4059  Qual foi o rendimento bruto que ... recebeu/fe...
613       1.0      V40591  Recebeu/fez nesse(s) outro(s) trabalho(s) rend...
615       1.0     V405911  Número da faixa do rendimento/retirada em dinh...
625       8.0     V405912  Valor em dinheiro do rendimento mensal que rec...
627       1.0      V40592  Recebeu/fez nesse(s) outro(s) trabalhos no mês...
629       1.0     V405921  Número da faixa do rendimento/retirada em prod...
639       8.0     V405922  Valor estimado do produtos e mercadorias que r...
641       3.0       V4062  Quantas horas ... trabalhava normalmente, por ...
643       3.0      V4062C  Quantas horas ... trabalhou efetivamente na se...
645       1.0      V4063A  ... gostaria de trabalhar mais horas do que as...
648       1.0      V4064A  No mês de referência, ... estaria disponível p...
652       1.0       V4071  No período de ... a ... (período de referência...
655       1.0      V4072A  No período de ... a ... (período de referência...
665       1.0       V4073  Embora não tenha tomado providência para conse...
668       2.0      V4074A  Qual foi o principal motivo de ... não ter tom...
679       1.0      V4075A  Quanto tempo depois de ... (último dia da sema...
683       2.0     V4075A1  Número de meses para começar o trabalho que co...
685       1.0       V4076  Até o dia ... (último dia da semana de referên...
690       2.0      V40761  fazia quanto tempo que vinha procurando trabal...
692       2.0      V40762  fazia quanto tempo que vinha procurando trabal...
694       2.0      V40763  fazia quanto tempo vinha procurando trabalho (...
696       1.0       V4077  Se tivesse conseguido um trabalho, ... poderia...
699       1.0      V4078A  Qual foi o principal motivo para ... não quere...
706       1.0       V4082  No período de captação de 358 dias, ... trabal...
709       1.0       V4097  Na semana de referência era associado a algum ...
714       1.0      V5001A   No mês de ... (mês de referência), ... recebe...
716       8.0     V5001A2                        Valor efetivamente recebido
718       1.0      V5002A   No mês de ... (mês de referência), ... recebe...
720       8.0     V5002A2                        Valor efetivamente recebido
722       1.0      V5003A  No mês de ... (mês de referência), ... recebeu...
724       8.0     V5003A2                        Valor efetivamente recebido
727       1.0      V5004A   No mês de ... (mês de referência), ... recebe...
729       8.0     V5004A2                        Valor efetivamente recebido
731       1.0      V5005A   No mês de ... (mês de referência), ... recebe...
733       8.0     V5005A2                        Valor efetivamente recebido
735       1.0      V5006A   No mês de ... (mês de referência), ... recebe...
737       8.0     V5006A2                        Valor efetivamente recebido
739       1.0      V5007A   No mês de ... (mês de referência), ... recebe...
741       8.0     V5007A2                        Valor efetivamente recebido
743       1.0      V5008A   No mês de ... (mês de referência), ... recebe...
745       8.0     V5008A2                        Valor efetivamente recebido
748       1.0      S01001                         Este domicílio é do tipo:
751       1.0      S01002  Qual é o material que predomina na construção ...
757       1.0      S01003  Qual é o material que predomina na cobertura (...
763       1.0      S01004  Qual é o material que predomina no piso deste ...
768       2.0      S01005                Quantos cômodos tem este domicílio?
769       2.0      S01006  Quantos cômodos estão servindo permanentemente...
770       1.0      S01007  Qual é a principal forma de abastecimento de á...
776       1.0     S01007A  Este domicílio tem acesso a rede geral de dist...
779       1.0      S01008  Nos últimos 30 dias, com que frequência a água...
784       1.0      S01009  Este domicílio dispõe ou faz uso de reservatór...
787       1.0      S01010            A água utilizada neste domicílio chega:
790       2.0     S01011A  Quantos banheiros (com chuveiro ou banheira e ...
791       2.0     S01011B  Quantos banheiros (com chuveiro ou banheira e ...
793       1.0     S01011C  Utiliza sanitário ou buraco para dejeções, inc...
796       1.0     S01012A  Para onde vai o esgoto do banheiro (sanitário ...
804       1.0      S01013         Qual é o (principal) destino dado ao lixo?
810       1.0      S01014  Qual(is) a(s) origem(ns) da energia elétrica u...
813       1.0     S010141      A origem da energia eletrica é de rede geral?
815       1.0     S010142  Há outra origem de energia eletrica (gerador, ...
817       1.0      S01015  Com que frequência a energia elétrica, proveni...
821       1.0     S01016A  No domicílio, normalmente, a preparação dos al...
823       1.0    S01016A1  Este domicilio utiliza gás de botijão na prepa...
825       1.0    S01016A2  Este domicilio utiliza gás encanado na prepara...
827       1.0    S01016A3  Este domicilio utiliza lenha ou carvão na prep...
829       1.0    S01016A4  Este domicilio utiliza energia eletrica na pre...
831       1.0    S01016A5  Este domicilio utiliza outro combustivel na pr...
833       1.0     S01016B                    Qual desses é o mais utilizado?
839       1.0      S01017                                 Este domicílio é:
846       8.0      S01018  Qual foi o valor mensal da prestação paga, ou ...
848       8.0      S01019  Qual foi o valor mensal do aluguel pago, ou qu...
850       1.0      S01020  O terreno onde está localizado este domicílio ...
852       1.0     S01020A  Esse domicílio tem algum documento que comprov...
855       2.0      S01021  Neste domicílio, quantos moradores têm telefon...
856       1.0      S01022     Este domicílio tem telefone fixo convencional?
858       1.0      S01023                      Este domicílio tem geladeira?
861       1.0      S01024         Este domicílio tem máquina de lavar roupa?
863       1.0      S01025                      Este domicílio tem televisão?
867       1.0      S01026  Este domicílio possui serviço de televisão por...
870       1.0      S01028  Este domicílio tem microcomputador (considere ...
872       1.0      S01029  Algum morador tem acesso à Internet no domicíl...
874       1.0      S01031  Algum morador deste domicílio tem automóvel ou...
876       1.0     S010311  Algum morador deste domicilio tem automóvel pa...
878       1.0     S010312  Algum morador deste domicilio tem motocicleta ...
881       2.0      VD2002                              Condição no domicílio
898       2.0      VD2003  Número de componentes do domicílio (exclusive ...
899       1.0      VD2004                       Espécie da unidade doméstica
903       2.0      VD2006  Faixas etárias utilizadas no processo de calib...
920       1.0      VD3004  Nível de instrução mais elevado alcançado (pes...
928       2.0      VD3005  Anos de estudo (pessoas de 5 anos ou mais de i...
946       1.0      VD3006  Grupos de anos de estudo (pessoas de 5 anos ou...
953       1.0      VD4001  Condição em relação à força de trabalho na sem...
956       1.0      VD4002  Condição de ocupação na semana de referência p...
959       1.0      VD4003  Força de trabalho potencial para pessoas de 14...
962       1.0     VD4004A  Subocupação por insuficiência de horas habitua...
964       1.0      VD4005       Pessoas desalentadas na semana de referência
966       1.0      VD4007  Posição na ocupação no trabalho principal da s...
971       1.0      VD4008  Posição na ocupação no trabalho principal da s...
978       2.0      VD4009  Posição na ocupação e categoria do emprego do ...
989       2.0      VD4010  Grupamentos de atividade principal do empreend...
1002      2.0      VD4011  Grupamentos ocupacionais do trabalho principal...
1014      1.0      VD4012  Contribuição para instituto de previdência em ...
1017      1.0      VD4013  Faixa das horas habitualmente trabalhadas por ...
1023      1.0      VD4014  Faixa das horas efetivamente trabalhadas na se...
1029      1.0      VD4015  Tipo de remuneração habitualmente recebida no ...
1032      8.0      VD4016  Rendimento mensal habitual do trabalho princip...

In [13]:
pnadc = pnadium.anual.download(2024,1,'v',colunas=['UF','S01014','S01008'])

Iniciou o download: Visita 1/2024 - aguarde.
Download finalizado.
Iniciou a criação do DataFrame Pandas: esta etapa pode demorar alguns minutos.
Chunks processados e salvos.
DataFrame criado.

,UF,UPA,V1008,V1014,V2003,S01008,S01014,COD_FAM,COD_PESSOA
0,11,110000016,03,11,01,1.0,1,1100000160311,110000016031101
1,11,110000016,06,11,01,1.0,1,1100000160611,110000016061101
2,11,110000016,06,11,02,1.0,1,1100000160611,110000016061102
3,11,110000016,08,11,01,1.0,1,1100000160811,110000016081101
4,11,110000016,08,11,02,1.0,1,1100000160811,110000016081102
5,11,110000016,09,11,01,1.0,1,1100000160911,110000016091101
6,11,110000016,09,11,02,1.0,1,1100000160911,110000016091102
7,11,110000016,10,11,01,1.0,1,1100000161011,110000016101101
8,11,110000016,10,11,02,1.0,1,1100000161011,110000016101102
9,11,110000016,11,11,01,1.0,1,1100000161111,110000016111101

In [16]:
display(pnadc.head(10))
display(pnadc.shape)
display(pnadc.describe())
display(pnadc.info())

,UF,UPA,V1008,V1014,V2003,S01008,S01014,COD_FAM,COD_PESSOA
0,11,110000016,03,11,01,1.0,1,1100000160311,110000016031101
1,11,110000016,06,11,01,1.0,1,1100000160611,110000016061101
2,11,110000016,06,11,02,1.0,1,1100000160611,110000016061102
3,11,110000016,08,11,01,1.0,1,1100000160811,110000016081101
4,11,110000016,08,11,02,1.0,1,1100000160811,110000016081102
5,11,110000016,09,11,01,1.0,1,1100000160911,110000016091101
6,11,110000016,09,11,02,1.0,1,1100000160911,110000016091102
7,11,110000016,10,11,01,1.0,1,1100000161011,110000016101101
8,11,110000016,10,11,02,1.0,1,1100000161011,110000016101102
9,11,110000016,11,11,01,1.0,1,1100000161111,110000016111101

(381815, 9)

                  UF         S01008         S01014
count  381815.000000  299588.000000  381815.000000
mean       31.021251       1.247149       1.002944
std        10.952716       0.663423       0.054177
min        11.000000       1.000000       1.000000
25%        23.000000       1.000000       1.000000
50%        31.000000       1.000000       1.000000
75%        41.000000       1.000000       1.000000
max        53.000000       4.000000       2.000000

<class 'pandas.DataFrame'>
RangeIndex: 381815 entries, 0 to 381814
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   UF          381815 non-null  int64
 1   UPA         381815 non-null  str
 2   V1008       381815 non-null  str
 3   V1014       381815 non-null  str
 4   V2003       381815 non-null  str
 5   S01008      299588 non-null  float64
 6   S01014      381815 non-null  int64
 7   COD_FAM     381815 non-null  str
 8   COD_PESSOA  381815 non-null  str
dtypes: float64(1), int64(2), str(6)
memory usage: 41.9 MB

None